<a href="https://colab.research.google.com/github/manal432567-oss/CSC1203-week1---reema/blob/main/Lab9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.arange(5, 25).reshape(4, 5)

print("A=\n", A)
print("dtype:", A.dtype)
print("ndim:", A.ndim)
print("shape:", A.shape)
print("size:", A.size)
print("itemsize:", A.itemsize)

B = A.reshape(5, 4)

print("\nB=\n", B)
print("B shape:", B.shape)

A=
 [[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
dtype: int64
ndim: 2
shape: (4, 5)
size: 20
itemsize: 8

B=
 [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
B shape: (5, 4)


In [2]:
import numpy as np

a = np.array([[5., 5., 5.],
              [15., 15., 15.],
              [25., 25., 25.]])

b = np.array([2., 4., 6.])

c = a + b

print("c=\n", c)

mask = (c >= 28)

print("\nMask=\n", mask)

count = mask.sum()

print("\nCount:", count)

c=
 [[ 7.  9. 11.]
 [17. 19. 21.]
 [27. 29. 31.]]

Mask=
 [[False False False]
 [False False False]
 [False  True  True]]

Count: 2


In [3]:
import numpy as np

grades = np.array([[90, 85, 78],
                   [88, 91, 95],
                   [76, 84, 89]])

print("Sum:", np.sum(grades))
print("Min:", np.min(grades))
print("Max:", np.max(grades))
print("Mean:", np.mean(grades))
print("STD:", np.std(grades))
print("VAR:", np.var(grades))

print("Mean per column:", np.mean(grades, axis=0))
print("Mean per row:", np.mean(grades, axis=1))

print("Max per row:", np.max(grades, axis=1))

Sum: 776
Min: 76
Max: 95
Mean: 86.22222222222223
STD: 5.807615264609768
VAR: 33.728395061728385
Mean per column: [84.66666667 86.66666667 87.33333333]
Mean per row: [84.33333333 91.33333333 83.        ]
Max per row: [90 95 89]


In [4]:
import numpy as np

table = np.array([[5, 8, 2, 7],
                  [1, 9, 4, 3],
                  [6, 0, 11, 10],
                  [12, 13, 14, 15]])

print("Second row:", table[1])

print("Third column:", table[:, 2])

print("Sub table:\n", table[1:3, 1:3])

Second row: [1 9 4 3]
Third column: [ 2  4 11 14]
Sub table:
 [[ 9  4]
 [ 0 11]]


In [5]:
import numpy as np

scores = np.array([[70, 80, 90],
                   [60, 75, 85],
                   [88, 92, 79],
                   [55, 65, 72]])

scores[:, 1] += 5

scores[0] = [100, 100, 100]

scores[:, 2] = 0

print(scores)

[[100 100   0]
 [ 60  80   0]
 [ 88  97   0]
 [ 55  70   0]]


In [6]:
import numpy as np

A = np.array([[2, 3],
              [4, 5]])

B = np.array([[1, 6],
              [7, 8]])

v = np.array([3, 5])

print("Element-wise:\n", A * B)

print("Matrix multiplication:\n", A @ B)

print("Broadcasting:\n", A * v)

Element-wise:
 [[ 2 18]
 [28 40]]
Matrix multiplication:
 [[23 36]
 [39 64]]
Broadcasting:
 [[ 6 15]
 [12 25]]


In [7]:
import numpy as np

np.random.seed(1)

matrix = np.random.randint(-5, 6, size=(4, 4))

print(matrix)

unique_values, counts = np.unique(matrix, return_counts=True)

print("Unique values:", unique_values)
print("Counts:", counts)

print("Unique rows:\n", np.unique(matrix, axis=0))

[[ 0  3  4  0]
 [-5 -5 -4  2]
 [ 1  4 -3 -1]
 [ 0 -3 -1  5]]
Unique values: [-5 -4 -3 -1  0  1  2  3  4  5]
Counts: [2 1 2 2 3 1 1 1 2 1]
Unique rows:
 [[-5 -5 -4  2]
 [ 0 -3 -1  5]
 [ 0  3  4  0]
 [ 1  4 -3 -1]]


In [8]:
import numpy as np

x = np.array([4, 2, 7, 1, 9, 5, 3])

A = np.array([[8, 6, 2],
              [1, 7, 4]])

indices = np.argsort(x)

print("Indices:", indices)

print("Sorted x:", x[indices])

min_location = np.unravel_index(A.argmin(), A.shape)

print("Min location:", min_location)

print("Indices > 3:", np.where(x > 3))

print("Split arrays:", np.split(x, [2, 5]))

expanded = np.expand_dims(x, axis=0)

print("Expanded:\n", expanded)

print("Squeezed:", np.squeeze(expanded))

Indices: [3 1 6 0 5 2 4]
Sorted x: [1 2 3 4 5 7 9]
Min location: (np.int64(1), np.int64(0))
Indices > 3: (array([0, 2, 4, 5]),)
Split arrays: [array([4, 2]), array([7, 1, 9]), array([5, 3])]
Expanded:
 [[4 2 7 1 9 5 3]]
Squeezed: [4 2 7 1 9 5 3]
